mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from .api_router import router
from django.views.generic.base import RedirectView

from mysite import views

urlpatterns = [
    path('', RedirectView.as_view(url='sahakorn/')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('sahakorn/', include("sahakorn.urls")),
]

sahakorn/urls.py
from django.urls import path
from . import views

app_name = "sahakorn"
urlpatterns = [
    path("", views.MemberListView.as_view(), name="index"),
    path("equipment/", views.EquipmentView.as_view(), name="equipment"),
    path("market/", views.MarketView.as_view(), name="market"),
    path("finance/", views.FinanceView.as_view(), name="finance"),
    path("inventory/", views.InventoryView.as_view(), name="inventory"),
    path("transaction/", views.TransactionView.as_view(), name="transaction"),
    path("profile/", views.ProfileView.as_view(), name="profile")
]

sahakorn/models/borrowing.py
from django.db import models
from .equipment import Equipment
from .member import Member


class Borrowing(models.Model):
    """Models to record equipment borrowing"""
    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(
                    r_date__gte=models.F("s_date")
                ),
                name="equipment must be return after borrowing date.",
            )
        ]

    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    user = models.ForeignKey(Member, on_delete=models.CASCADE)
    s_date = models.DateField()
    r_date = models.DateField()

    def __str__(self):
        return (
            f"{self.user} borrows {self.equipment} from {self.s_date} to {self.r_date}"
        )

    @property
    def borrower_name(self):
        return self.user.name

sahakorn/models/common_fee.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from calendar import month_name
from .member import Member


class CommonFee(models.Model):
    """A record to store common fee payment of a member"""

    month = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(12)]
    )
    year = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(9999)]
    )
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    total_paid = models.FloatField(validators=[MinValueValidator(0)])
    total_due = models.FloatField(validators=[MinValueValidator(0)], default=100)

    def get_month(self) -> str:
        """Get the actual month name from month field, which is from 1-12."""
        return month_name[self.month]

    def __str__(self):
        return f"Fee of {self.member} on {self.get_month()} {self.year}"

sahakorn/models/equipment.py
from django.db import models
from .member import Member


class Equipment(models.Model):
    """The model to store co-op equipments"""

    name = models.CharField(max_length=300)
    owner = models.ForeignKey(Member, on_delete=models.CASCADE)
    equipment_type = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f"{self.name} of {self.owner}"

    @property
    def owner_name(self):
        return self.owner.name

sahakorn/models/item_type.py
from django.db import models


class ItemType(models.Model):
    """Model for Item Type"""

    name = models.CharField(max_length=300)
    color = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.name

sahakorn/models/loans.py
from django.db import models
from django.core.validators import MinValueValidator
from .member import Member


class Loans(models.Model):
    """Model to record loans taken by members"""

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(
                    paid__lte=models.F("amount"),
                ),
                name="paid amount less than borrow amount",
            )
        ]

    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    amount = models.FloatField(validators=[MinValueValidator(0)])
    loan_date = models.DateField()
    paid = models.FloatField(validators=[MinValueValidator(0)], default=0)

    def __str__(self):
        return f"Loan of {self.member} from {self.loan_date}"

sahakorn/models/market_item.py
from django.db import models
from django.core.validators import MinValueValidator
from .stock import Stock


class MarketItem(models.Model):
    """Model for Market items"""

    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    quantity = models.IntegerField(validators=[MinValueValidator(0)])
    price = models.IntegerField(validators=[MinValueValidator(0)])

    @property
    def p_name(self) -> str:
        """Get product name."""
        return self.stock.p_name

    @property
    def member(self) -> str:
        """return the god damn member"""
        return self.stock.member

    def __str__(self):
        return f"{self.p_name} x {self.quantity} by {self.member} "

sahakorn/models/member.py
"""The member model."""

from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from .producer_type import ProducerType


class Member(models.Model):
    """The model for a certain co-op member."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    produce_type = models.ManyToManyField(ProducerType)

    def __str__(self) -> str:
        return self.name

    @receiver(post_save, sender=User)
    def member_create(sender, instance=None, created=False, **kwargs):
        if created:
            Member.objects.create(user=instance, name=instance.username)

sahakorn/models/producer_type.py
from django.db import models

class ProducerType(models.Model):
    """Model to record what type of produce a member produce."""
    
    name = models.CharField(max_length=300)
    color = models.CharField(max_length=30)

sahakorn/views/borrowing.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework import serializers
from rest_framework.serializers import ModelSerializer
from sahakorn.models import Borrowing

class BorrowingSerializer(ModelSerializer):
    borrower_name = serializers.SerializerMethodField()

    class Meta:
        model = Borrowing
        fields = "__all__"

    def get_borrower_name(self, obj):
        return obj.borrower_name


class BorrowingViewSet(ModelViewSet):
    """A viewset for Borrowing model."""

    serializer_class = BorrowingSerializer
    
    def get_queryset(self):
        member = self.request.query_params.get("member")
        owner = self.request.query_params.get("owner")
        equipment_id = self.request.query_params.get("equipment")
        if member is not None:
            queryset = Borrowing.objects.filter(user=member)
        elif owner is not None:
            queryset = Borrowing.objects.filter(equipment__owner__user=self.request.user)
        elif equipment_id is not None:
            queryset = Borrowing.objects.filter(equipment__id = equipment_id)
        else:
            queryset = Borrowing.objects.all()
        return queryset

sahakorn/views/common_fee.py
from datetime import datetime
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework.serializers import ModelSerializer
from sahakorn.models import CommonFee


class CommonFeeSerializer(ModelSerializer):
    class Meta:
        model = CommonFee
        fields = "__all__"


class CommonFeeViewSet(ModelViewSet):
    """A viewset for common fee model."""

    queryset = CommonFee.objects.all()
    serializer_class = CommonFeeSerializer

    def create(self, request, *args, **kwargs):
        serializer = CommonFeeSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.validated_data
        obj, created = CommonFee.objects.get_or_create(
            month=data["month"], year=data["year"], member=data["member"],
            defaults={
                "month": data["month"],
                "year": data["year"],
                "total_paid": data["total_paid"],
                "member": data["member"]}
        )
        if not created:
            obj = CommonFee.objects.get(
                month=data["month"], year=data["year"], member=data["member"])
            obj.total_paid += data["total_paid"]
            obj.save()
        response_serializer = CommonFeeSerializer(obj)
        return Response(response_serializer.data, status=201)

    def retrieve(self, request, *args, **kwargs):
        user = request.user
        today = datetime.now()
        try:
            query = CommonFee.objects.get(
                member__id=user.id, month=today.month, year=today.year)
        except CommonFee.DoesNotExist:
            return Response(
                {"error": "no Common Fee this month", "total_paid": 0, "total_due": 100.0},
                status=status.HTTP_404_NOT_FOUND)
        serializer = CommonFeeSerializer(query)
        return Response(serializer.data, status=status.HTTP_200_OK)

    @action(detail=False, methods=["get"])
    def payment_status(self, request):
        queryset = CommonFee.objects.filter(member__user=request.user)
        if not queryset:
            return Response({"payment_status": "Late"}, status=status.HTTP_200_OK)
        q = queryset.last()

        if (
            datetime.now() >= datetime(q.year, q.month, 1)
            and q.total_due - q.total_paid > 0
        ):
            return Response({"payment_status": "Late"}, status=status.HTTP_200_OK)
        return Response({"payment_status": "Up to Date"}, status=status.HTTP_200_OK)

sahakorn/views/equipment.py
from rest_framework.viewsets import ModelViewSet
from rest_framework import serializers
from rest_framework.serializers import ModelSerializer
from sahakorn.models import Equipment

from django.views import generic


class EquipmentView(generic.TemplateView):
    template_name = "sahakorn/equipment.html"

class EquipmentSerializer(ModelSerializer):
    owner_name = serializers.SerializerMethodField()

    class Meta:
        model = Equipment
        fields = "__all__"

    def get_owner_name(self, obj):
        return obj.owner_name


class EquipmentViewSet(ModelViewSet):
    """A viewset for equipment model."""

    serializer_class = EquipmentSerializer

    def get_queryset(self):
        owner = self.request.query_params.get("owner")
        if owner is not None:
            print(self.request.user)
            queryset = Equipment.objects.filter(owner__user=self.request.user)
        else:
            queryset = Equipment.objects.all()
        return queryset

sahakorn/views/finance_template.py
from django.views import generic


class FinanceView(generic.TemplateView):
    template_name = "sahakorn/finance.html"

sahakorn/views/item_type.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.serializers import ModelSerializer
from sahakorn.models import ItemType


class ItemTypeSerializer(ModelSerializer):
    class Meta:
        model = ItemType
        fields = "__all__"


class ItemTypeViewSet(ModelViewSet):
    """A viewset for ItemType model."""

    queryset = ItemType.objects.all()
    serializer_class = ItemTypeSerializer

sahakorn/views/loans.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.serializers import ModelSerializer
from rest_framework.response import Response
from sahakorn.models import Loans


class LoansSerializer(ModelSerializer):
    class Meta:
        model = Loans
        fields = "__all__"


class LoansViewSet(ModelViewSet):
    """A viewset for Loans model."""

    serializer_class = LoansSerializer

    def get_queryset(self):
        member = self.request.query_params.get("member")
        if member is not None:
            return Loans.objects.filter(member__user=self.request.user).order_by("-loan_date")
        return Loans.objects.all().order_by("-loan_date")

    def update(self, request, *args, **kwargs):
        loan = self.get_object()
        serializer = LoansSerializer(data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        loan.paid += serializer.validated_data["paid"]
        loan.save()
        response_serializer = LoansSerializer(loan)
        return Response(response_serializer.data, status=200)

sahakorn/views/market_item.py
from rest_framework.viewsets import ModelViewSet
from rest_framework import serializers, status
from rest_framework.response import Response
from rest_framework.serializers import ModelSerializer
from sahakorn.models import MarketItem, Stock
from django.views import generic


class MarketView(generic.TemplateView):
    template_name = "sahakorn/market.html"

class MarketItemSerializer(ModelSerializer):
    producer = serializers.SerializerMethodField()
    
    class Meta:
        model = MarketItem
        fields = "__all__"

    def get_producer(self, obj):
        return obj.member.name


class MarketItemViewSet(ModelViewSet):
    """A viewset for MarketItem model."""

    serializer_class = MarketItemSerializer
    
    def get_queryset(self):
        item_type = self.request.query_params.get("item_type")
        order = self.request.query_params.get("order")
        if item_type and order:
            return MarketItem.objects.filter(stock__item_type__name=item_type).order_by(order)
        if item_type is not None:
            return MarketItem.objects.filter(stock__item_type__name=item_type)
        if order is not None:
            return MarketItem.objects.order_by(order)
        return MarketItem.objects.all()

    def create(self, request):
        data = request.data
        serializer = MarketItemSerializer(data=data)
        try:
            stock = Stock.objects.get(id=data["stock"])
        except Stock.DoesNotExist:
            return Response({"error": "Stock does not exist"}, status=status.HTTP_400_BAD_REQUEST)
        if serializer.is_valid():
            stock.quantity -= int(data["quantity"])
            stock.save()
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

sahakorn/views/member.py
from typing import Any
from django.db.models import QuerySet
from django.views.generic import ListView
from rest_framework.viewsets import ModelViewSet
from rest_framework.serializers import ModelSerializer
from rest_framework.response import Response
from sahakorn.models import Member, ProducerType
from .producer_type import ProducerTypeSerializer


class MemberListView(ListView):
    template_name = "sahakorn/member.html"
    context_object_name = "members"

    def get_queryset(self) -> QuerySet[Any]:
        return Member.objects.all()


class MemberSerializer(ModelSerializer):
    produce_type = ProducerTypeSerializer(many=True, read_only=True)

    class Meta:
        model = Member
        fields = "__all__"


class MemberViewSet(ModelViewSet):
    """A viewset for Member model."""

    queryset = Member.objects.all()
    serializer_class = MemberSerializer

    def create(self, request, *args, **kwargs):
        user = self.request.user
        username = user.username
        data = self.request.data
        name = data["name"]
        Member.objects.filter(user=user).update(name=name)
        member = Member.objects.get(user=user)
        member = MemberSerializer(member)
        return Response({"profile": member.data, "username": str(username)})

    def update(self, request, *args, **kwargs):
        user = self.request.user
        username = user.username
        member = Member.objects.get(user=user)
        serializer = MemberSerializer(member, data=request.data, partial=True)
        if serializer.is_valid():
            updated = serializer.save()
            updated.produce_type.clear()
            for tag_id in request.data.get('produce_type'):
                tag = ProducerType.objects.get(id=tag_id)
                updated.produce_type.add(tag)
            return Response({"profile": serializer.data, "username": str(username)})
        return Response({"error": serializer.errors})

sahakorn/views/producer_type.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.serializers import ModelSerializer
from sahakorn.models import ProducerType


class ProducerTypeSerializer(ModelSerializer):
    class Meta:
        model = ProducerType
        fields = "__all__"


class ProducerTypeViewSet(ModelViewSet):
    """A viewset for ProducerType model."""

    queryset = ProducerType.objects.all()
    serializer_class = ProducerTypeSerializer

sahakorn/views/profile.py
from typing import Any
from django.views.generic import TemplateView
from sahakorn.models import Member

class ProfileView(TemplateView):
    template_name = "sahakorn/profile.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        profile = Member.objects.get(user=self.request.user)
        context["profile"] = profile
        return context

sahakorn/templates/sahakorn/base.html
<!DOCTYPE html>
<html lang="en" data-theme="cyberpunk">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.14/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js" defer></script>
    {% load static %}
    {% block headcontent %}
    {% endblock %}
  </head>
  <body>
    <div class="navbar bg-base-100">
      <div class="flex-1">
        <a class="btn btn-ghost text-xl" href="{% url 'sahakorn:index' %}">Sahakorn</a>
      </div>
      <div class="flex-none gap-2">
        {% if not user.is_authenticated %}
          <ul class="menu menu-horizontal px-1">
            <li><a href="{% url 'login' %}?next={{request.path}}" class="button auth-button">
                Login
            </a></li>
            <li><a href="{% url 'signup' %}?next={{request.path}}" class="button auth-button">
                Sign-up
            </a></li>
          </ul>
      {% else %}
        <ul class="menu menu-horizontal px-1">
          <li><a href="{% url 'sahakorn:market' %}" class="button auth-button">
            Market
          </a></li>
          <li><a href="{% url 'sahakorn:transaction' %}" class="button auth-button">
            Transactions
          </a></li>
          <li><a href="{% url 'sahakorn:inventory' %}" class="button auth-button">
            Inventory
          </a></li>
          <li><a href="{% url 'sahakorn:finance' %}" class="button auth-button">
            Finance
          </a></li>
          <li><a href="{% url 'sahakorn:equipment' %}" class="button auth-button">
            Equipment
          </a></li>
        </ul>

        <div class="dropdown dropdown-end">
          <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
            <div class="w-10 rounded-full">
              <img alt="Profile Pic" src="{% static 'sahakorn/images/image.png' %}">
            </div>
          </div>
          <ul
            tabindex="0"
            class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
            <li>
              <p>{{ user.username }}<p>
            </li>
            <li>
              <a class="justify-between" href="{% url 'sahakorn:profile' %}">
                Profile
              </a>
            </li>
            <li>
              <form action="{% url 'logout' %}" method="post" class="header-container"> 
                {% csrf_token %}
                <button type="submit" class="button auth-button">Log Out</button> 
              </form>
            </li>
          </ul>
        </div>
      {% endif %}
      </div>
    </div>
  
    {% if messages %}
      <ul class="messages">
      {% for message in messages %}
        <li class="{{message.tags}} center-text">
          {{message}}
        </li>
      {% endfor %}
      </ul>
    {% endif %}
  
    <div>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

sahakorn/templates/sahakorn/equipment.html
{% extends 'sahakorn/base.html' %}

{% block headcontent %}
<title>
  Equipment Borrowing | Sahakorn
</title>
{% load static %}
<script src="{% static 'sahakorn/equipment.js' %}" defer type="module"></script>
{{ request.user.id|json_script:"user_id" }}
{% endblock %}


{% block content %}
<div class="container p-4">


  <button class="btn btn-primary" id="all-equipments">All Equipments</button>
  <button class="btn btn-primary" id="lent-equipments">Lent Equipments</button>
  <button class="btn btn-secondary" id="my-equipments">My Equipments</button>
  <button class="btn btn-secondary" id="register-equipment" onclick="addModal.showModal()">Register Equipment</button>

  <table class="table table-zebra w-full">
    <thead>
      <tr>
        <th>Equipment</th>
        <th>Type</th>
        <th>Owner</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody id="equipments-table">

    </tbody>
  </table>

  <dialog id="borrowModal" class="modal">
    <div class="modal-box">
      <h2 class="text-xl font-bold">Borrow</h2>
      <form id="borrowForm">
        <div class="mb-4">
          <label for="r_date" class="block">Borrow till:</label>
          <input type="date" id="r_date" name="r_date" class="input input-bordered w-full">
        </div>

        <div class="modal-action">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
    <form method="dialog" class="modal-backdrop">
      <button>close</button>
    </form>
  </dialog>

  <dialog id="addModal" class="modal">
    <div class="modal-box">
      <h2 class="text-xl font-bold">Add Equipment</h2>
      <form id="addForm">
        <div class="mb-4">
          <label for="name" class="block">Equipment name:</label>
          <input type="text" id="name" name="name" class="input input-bordered w-full">
        </div>

        <div class="mb-4">
          <label for="equipment-type" class="block">Equipment type:</label>
          <input type="text" id="equipment-type" name="equipment-type" class="input input-bordered w-full">
        </div>

        <div class="modal-action">
          <button type="submit" class="btn btn-primary">Register</button>
        </div>
      </form>
    </div>
    <form method="dialog" class="modal-backdrop">
      <button>close</button>
    </form>
  </dialog>

</div>

{% endblock %}

sahakorn/templates/sahakorn/finance.html
{% extends "sahakorn/base.html" %}

{% block headcontent %}
<title>Finance | Sahakorn</title>
{% load static %}
<script src="{% static 'sahakorn/finance.js' %}" defer type="module"></script>
{{ request.user.id|json_script:"user_id" }}
{% endblock %}


{% block content %}
<div class="container mx-auto p-6">
  <!-- Page Title -->
  <h1 class="text-3xl font-bold mb-6">Common Fee & Loans</h1>

  <!-- Common Fee Payment Status -->
  <div class="mb-6">
    <h2 class="text-xl font-semibold">Common Fee Payment Status</h2>
    <div class="alert alert-info shadow-lg mt-4 flex justify-between items-center">
      <div>
        <span>
          Your payment status: <span class="font-bold" id="payment-status">Never gonna give you up</span>
        </span>
      </div>
      <div id="common-fee-btn-container"></div>
    </div>
  </div>

  <!-- Number of Loans Taken -->
  <div class="mb-6">
    <h2 class="text-xl font-semibold">Loans Taken</h2>
    <div class="alert alert-success shadow-lg mt-4 flex justify-between items-center">
      <div>
        <span>You have taken out <span class="font-bold" id="loans-taken">Never gonna let you down</span>.</span>
      </div>
      <button onclick="takeLoanModal.showModal()">Take a Loan</button>
    </div>
  </div>

  <!-- Loans Table -->
  <div>
    <h2 class="text-xl font-semibold mb-4">Loans Details</h2>
    <div class="overflow-x-auto">
      <table class="table table-zebra w-full">
        <thead>
          <tr>
            <th>#</th>
            <th>Due Date</th>
            <th>Amount Paid</th>
            <th>Total Amount</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody id="loans-table">

        </tbody>
      </table>
    </div>
  </div>
</div>

<dialog id="commonFeeModal" class="modal">
  <div class="modal-box">
    <h2 class="text-xl font-bold">Pay Common Fee</h2>
    <form id="commonFeeForm">
      <div class="mb-4">
        <p class="mt-3">Paid: <span id="common-fee-paid">0</span>/<span id="common-fee-cost">100</span></p>
        <label for="total_paid" class="block mt-2">Payment Amount:</label>
        <input type="number" id="total_paid" name="total_paid" class="input input-bordered w-full">
      </div>
      
      <div class="modal-action">
        <button type="submit" id="buy-btn" class="btn btn-primary">Pay</button>
      </div>
    </form>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

<dialog id="takeLoanModal" class="modal">
  <div class="modal-box">
    <h2 class="text-xl font-bold mb-3">Take a Loan</h2>
    <form id="takeLoanForm">
      <div class="mb-4">
        <label for="loan_date" class="block">Due date:</label>
        <input type="date" id="loan_date" name="loan_date" class="input input-bordered w-full">
      </div>

      <div class="mb-4">
        <label for="amount" class="block mt-2">Loan Amount:</label>
        <input type="number" id="amount" name="amount" class="input input-bordered w-full">
      </div>
      
      <div class="modal-action">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

<dialog id="payLoanModal" class="modal">
  <div class="modal-box">
    <h2 class="text-xl font-bold mb-3">Pay off Loan</h2>
    <form id="payLoanForm">
      <div class="mb-4">
        <label for="paid" class="block">Payment amount:</label>
        <input type="number" id="paid" name="paid" class="input input-bordered w-full">
      </div>

      <div class="modal-action">
        <button type="submit" id="buy-btn" class="btn btn-primary">Pay</button>
      </div>
    </form>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>
{% endblock %}

sahakorn/templates/sahakorn/inventory.html
{% extends 'sahakorn/base.html' %}

{% block headcontent %}
<title>
  inventory | Sahakorn
</title>
{% load static %}
<script src="{% static 'sahakorn/inventory.js' %}" defer type="module"></script>
{{ request.user.id|json_script:"user_id" }}
{% endblock %}


{% block content %}
<div>
  <div class="container mx-auto p-5">
    <h1 class="text-3xl font-bold mb-6">My stock</h1>
    <div class="mb-4 flex space-x-4" id="filter-buttons">
      <button class="btn btn-secondary" id="add-item" onclick="addModal.showModal()">Register items</button>
      <select name="filter" id="filter" class="select select-bordered w-full">
      <option selected value>ALL TYPES</option>
      </select>
    </div>
    <div class="overflow-x-auto">
      {% if stock_items %}
      <table class="table table-zebra w-full">
        <thead>
          <tr>
            <th>Name</th>
            <th>Quantity</th>
            <th>Type</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody id="Stock-table">
        </tbody>
      </table>
      {% else %}
      <div>You have no Stock! Register some items to fill your inventory.</div>
      {% endif %} 
    </div>
  </div>
</div>

<dialog id="addModal" class="modal">
  <div class="modal-box">
    <h2 class="text-xl font-bold">Add Stock</h2>
    <form id="addForm">
      <div class="mb-4">
        <label for="name" class="block">Stock name:</label>
        <input type="text" id="name" name="name" class="input input-bordered w-full">
      </div>

      <div class="mb-4">
        <label for="quantity" class="block">Quantity:</label>
        <input type="text" id="quantity" name="quantity" class="input input-bordered w-full">
      </div>

      <div class="mb-4">
        <label for="stock-type" class="block">Stock Type(s):</label>
        <select id="stock-type" name="stock-type" class="select select-bordered w-full" multiple>
        </select>
      </div>

      <div class="modal-action">
        <button type="submit" class="btn btn-primary">Add to inventory</button>
      </div>
    </form>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

<dialog id="sellModal" class="modal">
  <div class="modal-box">
    <h2 class="text-xl font-bold">Sell</h2>
    <form id="sellForm">
      <div class="mb-4">
        <label for="quantity" class="block">Quantity:</label>
        <input type="number" id="quantity" name="quantity" class="input input-bordered w-full">
      </div>

      <div class="mb-4">
        <label for="price" class="block">Price:</label>
        <input type="number" id="price" name="price" class="input input-bordered w-full">
      </div>

      <div class="modal-action">
        <button type="submit" id="buy-btn" class="btn btn-primary">Put on Sale</button>
      </div>
    </form>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>
{% endblock %}

sahakorn/templates/sahakorn/member.html
{% extends 'sahakorn/base.html' %}


{% block content %}

<div class="container p-4">
  <h1>Sahakorn members</h1>
  {% for member in members %}
  {{member.name}} <br>
  {% endfor %}
</div>

{% endblock %}